version: 2
jobs:

  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: "Display Python Version"
          command: python --version
      - run:
          name: "Install awscli"
          command: sudo pip install awscli
      - run:
        name: "Build Docker Image"
        command: docker build -t circleci-practice .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
