version: 2
jobs:
  build:
    docker:
      - image: python:3.6.5-apline3.7
    steps:
      - checkout
      - run:
          name: "Display Python Version"
          command: python3 --version
      - run:
          name: "Install awscli"
          command: sudo pip install awscli

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
