version: 2
jobs:

  build:
    docker:
      - image: docker:18.05.0-ce-git
    # working_directory: ~/circleci-practice
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash \
              python3 \
              py3-pip \
              zip
      - run:
          name: Install awscli
          command: pip3 install awscli awsebcli
      - run:
          name: Zip files
          command: zip -r circleci-practice.zip .elasticbeanstalk Dockerrun.aws.json
      - run:
          name: List files
          command: pwd && ls -al
      - run:
          name: Deploy to S3
          command: aws s3 --region us-east-1 cp circleci-practice.zip s3://cs-s3aws-us-east --acl public-read
      - run:
          name: Build Docker Image
          command: docker build -t circleci-practice .
      - run: 
          name: Tag Docker Image
          command: docker tag circleci-practice:latest 276282166840.dkr.ecr.us-east-1.amazonaws.com/circleci-practice:latest
      - run:
          name: AWS ECR Login
          command: eval $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
          name: Push Docker Image to AWS ECR
          command: docker push 276282166840.dkr.ecr.us-east-1.amazonaws.com/circleci-practice 
      - run:
          name: Push S3 bundle to Elastic Beanstalk
          command: aws elasticbeanstalk --region us-east-1 create-application-version --application-name="CircleCI Practice" --version-label circleci-practice-dev-$CIRCLE_BUILD_NUM --source-bundle S3Bucket=cs-s3aws-us-east,S3Key=circleci-practice.zip
      - run:
          name: Update/Deploy to Elastic Beanstalk environment
          command: aws elasticbeanstalk --region us-east-1 update-environment --environment-name cs-practice-1 --version-label circleci-practice-dev-$CIRCLE_BUILD_NUM
      - run:
          name: Deploy to Elastic Beanstalk environment
          command: eb deploy cs-practice-1 --profile personal
        

