earlversion: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
        name: "Install awscli"
        command: sudo pip install awscli
  deploy-dev:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - run:
        name: "Deploy docker image to AWS"
        command: aws s3 sync /home/ubuntu/S3ContinuousDeploy s3://cs-s3aws-us-east --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      # - deploy-dev:
      #   requires:
      #     - build
      #   filters:
      #     branches:
      #       only: master
