elversion: 2
jobs:

  build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Install dependencies"
          command: |
            apk add --no-cache bash \
              python3 \
              py3-pip
      - run:
          name: "Python version"
          command: python3 --version
      - run:
          name: "Install awscli"
          command: pip3 install awscli
      - run:
          name: "Build Docker Image"
          command: docker build -t circleci-practice .
      - run:
          name: "AWS ECR Login"
          command: aws ecr get-login --no-include-email
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
