elversion: 2
jobs:

  build:
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "List files"
          command: ls -al
      - run:
          name: "Build Docker Image"
          command: docker pull golang:1.10.2-alpine3.7
      # - run:
      #     name: "Install Bash"
      #     command: apk --no-cache add bash
      - run:
          name: "Install dependencies"
          command: |
            apk add --no-cache bash

      - run:
          name: "Install awscli"
          command: sudo pip install awscli
      
      - run:
          name: "Build Docker Image"
          command: docker build -t circleci-practice .
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
